### ISSUE TITLE
Unable to pass `--id` into args

### ISSUE THREAD

**Issue by iamjaredwalters** [livecycle/preevy-up-action#8]
Doing so will result in a failure to find the compose file. Passing in both the the `-f` and `--id` to `args` also fails because this [line](https://github.com/livecycle/preevy-up-action/blob/latest/action.yml#L49) does not consider `args`.

**Comment by royra** [comment]
@iamjaredwalters this should be fixed with the latest versions of the Preevy CLI and this action. Please reopen if it still happens.
